// <auto-generated />
using System;
using IIS_backend.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IIS_backend.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260307150733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IIS_backend.Domain.Entities.Competition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiscountValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.CompetitionCurrency", b =>
                {
                    b.Property<long>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.HasKey("CompetitionId", "CurrencyId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CompetitionCurrencies");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyName")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Day", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Date")
                        .IsUnique();

                    b.ToTable("Days");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.PaymentSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SelectedCurrencyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SelectedCurrencyId");

                    b.ToTable("PaymentSnapshots");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.PromoCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IssuedPromoCodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PaymentSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("UsedPromoCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssuedPromoCodeId")
                        .IsUnique();

                    b.HasIndex("PaymentSnapshotId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("UsedPromoCodeId")
                        .IsUnique()
                        .HasFilter("[UsedPromoCodeId] IS NOT NULL");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.TicketCreationRequestError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "TicketCode")
                        .IsUnique();

                    b.ToTable("TicketCreationRequestErrors");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.TicketItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DayId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("TicketId", "DayId")
                        .IsUnique();

                    b.ToTable("TicketItems");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Zone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceAddon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Characteristics")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.CompetitionCurrency", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.Competition", "Competition")
                        .WithMany("CompetitionCurrencies")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_backend.Domain.Entities.Currency", "Currency")
                        .WithMany("CompetitionCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Day", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.Competition", "Competition")
                        .WithMany("Days")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.PaymentSnapshot", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.Currency", "SelectedCurrency")
                        .WithMany()
                        .HasForeignKey("SelectedCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SelectedCurrency");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.PromoCode", "IssuedPromoCode")
                        .WithOne("IssuedTicket")
                        .HasForeignKey("IIS_backend.Domain.Entities.Ticket", "IssuedPromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IIS_backend.Domain.Entities.PaymentSnapshot", "PaymentSnapshot")
                        .WithMany()
                        .HasForeignKey("PaymentSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IIS_backend.Domain.Entities.PromoCode", "UsedPromoCode")
                        .WithOne("UsedTicket")
                        .HasForeignKey("IIS_backend.Domain.Entities.Ticket", "UsedPromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IssuedPromoCode");

                    b.Navigation("PaymentSnapshot");

                    b.Navigation("UsedPromoCode");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.TicketItem", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.Day", "Day")
                        .WithMany("TicketItems")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IIS_backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketItems")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_backend.Domain.Entities.Zone", "Zone")
                        .WithMany("TicketItems")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Ticket");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Zone", b =>
                {
                    b.HasOne("IIS_backend.Domain.Entities.Competition", "Competition")
                        .WithMany("Zones")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionCurrencies");

                    b.Navigation("Days");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Currency", b =>
                {
                    b.Navigation("CompetitionCurrencies");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Day", b =>
                {
                    b.Navigation("TicketItems");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.PromoCode", b =>
                {
                    b.Navigation("IssuedTicket")
                        .IsRequired();

                    b.Navigation("UsedTicket");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketItems");
                });

            modelBuilder.Entity("IIS_backend.Domain.Entities.Zone", b =>
                {
                    b.Navigation("TicketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
