/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationIndexRouteImport } from './routes/administration/index'
import { Route as TicketViewRouteImport } from './routes/ticket/view'
import { Route as TicketNewRouteImport } from './routes/ticket/new'
import { Route as AdministrationZoneIndexRouteImport } from './routes/administration/zone/index'
import { Route as AdministrationDayIndexRouteImport } from './routes/administration/day/index'
import { Route as AdministrationZoneNewRouteImport } from './routes/administration/zone/new'
import { Route as AdministrationZoneIdRouteImport } from './routes/administration/zone/$id'
import { Route as AdministrationDayNewRouteImport } from './routes/administration/day/new'
import { Route as AdministrationDayIdRouteImport } from './routes/administration/day/$id'
import { Route as AdministrationZoneIdEditRouteImport } from './routes/administration/zone/$id_.edit'
import { Route as AdministrationDayIdEditRouteImport } from './routes/administration/day/$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationIndexRoute = AdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketViewRoute = TicketViewRouteImport.update({
  id: '/ticket/view',
  path: '/ticket/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketNewRoute = TicketNewRouteImport.update({
  id: '/ticket/new',
  path: '/ticket/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationZoneIndexRoute = AdministrationZoneIndexRouteImport.update({
  id: '/administration/zone/',
  path: '/administration/zone/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationDayIndexRoute = AdministrationDayIndexRouteImport.update({
  id: '/administration/day/',
  path: '/administration/day/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationZoneNewRoute = AdministrationZoneNewRouteImport.update({
  id: '/administration/zone/new',
  path: '/administration/zone/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationZoneIdRoute = AdministrationZoneIdRouteImport.update({
  id: '/administration/zone/$id',
  path: '/administration/zone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationDayNewRoute = AdministrationDayNewRouteImport.update({
  id: '/administration/day/new',
  path: '/administration/day/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationDayIdRoute = AdministrationDayIdRouteImport.update({
  id: '/administration/day/$id',
  path: '/administration/day/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationZoneIdEditRoute =
  AdministrationZoneIdEditRouteImport.update({
    id: '/administration/zone/$id_/edit',
    path: '/administration/zone/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationDayIdEditRoute = AdministrationDayIdEditRouteImport.update({
  id: '/administration/day/$id_/edit',
  path: '/administration/day/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ticket/new': typeof TicketNewRoute
  '/ticket/view': typeof TicketViewRoute
  '/administration/': typeof AdministrationIndexRoute
  '/administration/day/$id': typeof AdministrationDayIdRoute
  '/administration/day/new': typeof AdministrationDayNewRoute
  '/administration/zone/$id': typeof AdministrationZoneIdRoute
  '/administration/zone/new': typeof AdministrationZoneNewRoute
  '/administration/day/': typeof AdministrationDayIndexRoute
  '/administration/zone/': typeof AdministrationZoneIndexRoute
  '/administration/day/$id/edit': typeof AdministrationDayIdEditRoute
  '/administration/zone/$id/edit': typeof AdministrationZoneIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ticket/new': typeof TicketNewRoute
  '/ticket/view': typeof TicketViewRoute
  '/administration': typeof AdministrationIndexRoute
  '/administration/day/$id': typeof AdministrationDayIdRoute
  '/administration/day/new': typeof AdministrationDayNewRoute
  '/administration/zone/$id': typeof AdministrationZoneIdRoute
  '/administration/zone/new': typeof AdministrationZoneNewRoute
  '/administration/day': typeof AdministrationDayIndexRoute
  '/administration/zone': typeof AdministrationZoneIndexRoute
  '/administration/day/$id/edit': typeof AdministrationDayIdEditRoute
  '/administration/zone/$id/edit': typeof AdministrationZoneIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ticket/new': typeof TicketNewRoute
  '/ticket/view': typeof TicketViewRoute
  '/administration/': typeof AdministrationIndexRoute
  '/administration/day/$id': typeof AdministrationDayIdRoute
  '/administration/day/new': typeof AdministrationDayNewRoute
  '/administration/zone/$id': typeof AdministrationZoneIdRoute
  '/administration/zone/new': typeof AdministrationZoneNewRoute
  '/administration/day/': typeof AdministrationDayIndexRoute
  '/administration/zone/': typeof AdministrationZoneIndexRoute
  '/administration/day/$id_/edit': typeof AdministrationDayIdEditRoute
  '/administration/zone/$id_/edit': typeof AdministrationZoneIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ticket/new'
    | '/ticket/view'
    | '/administration/'
    | '/administration/day/$id'
    | '/administration/day/new'
    | '/administration/zone/$id'
    | '/administration/zone/new'
    | '/administration/day/'
    | '/administration/zone/'
    | '/administration/day/$id/edit'
    | '/administration/zone/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ticket/new'
    | '/ticket/view'
    | '/administration'
    | '/administration/day/$id'
    | '/administration/day/new'
    | '/administration/zone/$id'
    | '/administration/zone/new'
    | '/administration/day'
    | '/administration/zone'
    | '/administration/day/$id/edit'
    | '/administration/zone/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/ticket/new'
    | '/ticket/view'
    | '/administration/'
    | '/administration/day/$id'
    | '/administration/day/new'
    | '/administration/zone/$id'
    | '/administration/zone/new'
    | '/administration/day/'
    | '/administration/zone/'
    | '/administration/day/$id_/edit'
    | '/administration/zone/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TicketNewRoute: typeof TicketNewRoute
  TicketViewRoute: typeof TicketViewRoute
  AdministrationIndexRoute: typeof AdministrationIndexRoute
  AdministrationDayIdRoute: typeof AdministrationDayIdRoute
  AdministrationDayNewRoute: typeof AdministrationDayNewRoute
  AdministrationZoneIdRoute: typeof AdministrationZoneIdRoute
  AdministrationZoneNewRoute: typeof AdministrationZoneNewRoute
  AdministrationDayIndexRoute: typeof AdministrationDayIndexRoute
  AdministrationZoneIndexRoute: typeof AdministrationZoneIndexRoute
  AdministrationDayIdEditRoute: typeof AdministrationDayIdEditRoute
  AdministrationZoneIdEditRoute: typeof AdministrationZoneIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/': {
      id: '/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AdministrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/view': {
      id: '/ticket/view'
      path: '/ticket/view'
      fullPath: '/ticket/view'
      preLoaderRoute: typeof TicketViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/new': {
      id: '/ticket/new'
      path: '/ticket/new'
      fullPath: '/ticket/new'
      preLoaderRoute: typeof TicketNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/zone/': {
      id: '/administration/zone/'
      path: '/administration/zone'
      fullPath: '/administration/zone/'
      preLoaderRoute: typeof AdministrationZoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/day/': {
      id: '/administration/day/'
      path: '/administration/day'
      fullPath: '/administration/day/'
      preLoaderRoute: typeof AdministrationDayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/zone/new': {
      id: '/administration/zone/new'
      path: '/administration/zone/new'
      fullPath: '/administration/zone/new'
      preLoaderRoute: typeof AdministrationZoneNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/zone/$id': {
      id: '/administration/zone/$id'
      path: '/administration/zone/$id'
      fullPath: '/administration/zone/$id'
      preLoaderRoute: typeof AdministrationZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/day/new': {
      id: '/administration/day/new'
      path: '/administration/day/new'
      fullPath: '/administration/day/new'
      preLoaderRoute: typeof AdministrationDayNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/day/$id': {
      id: '/administration/day/$id'
      path: '/administration/day/$id'
      fullPath: '/administration/day/$id'
      preLoaderRoute: typeof AdministrationDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/zone/$id_/edit': {
      id: '/administration/zone/$id_/edit'
      path: '/administration/zone/$id/edit'
      fullPath: '/administration/zone/$id/edit'
      preLoaderRoute: typeof AdministrationZoneIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/day/$id_/edit': {
      id: '/administration/day/$id_/edit'
      path: '/administration/day/$id/edit'
      fullPath: '/administration/day/$id/edit'
      preLoaderRoute: typeof AdministrationDayIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TicketNewRoute: TicketNewRoute,
  TicketViewRoute: TicketViewRoute,
  AdministrationIndexRoute: AdministrationIndexRoute,
  AdministrationDayIdRoute: AdministrationDayIdRoute,
  AdministrationDayNewRoute: AdministrationDayNewRoute,
  AdministrationZoneIdRoute: AdministrationZoneIdRoute,
  AdministrationZoneNewRoute: AdministrationZoneNewRoute,
  AdministrationDayIndexRoute: AdministrationDayIndexRoute,
  AdministrationZoneIndexRoute: AdministrationZoneIndexRoute,
  AdministrationDayIdEditRoute: AdministrationDayIdEditRoute,
  AdministrationZoneIdEditRoute: AdministrationZoneIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
